### ISSUE TITLE
Extra newlines added on save

### ISSUE THREAD

**Issue by turtlexiv** [aswinkumar863/smarty-vscode-support#4] opened 2020-05-13 17:20 UTC
The extension seems to be adding extra newlines on each save.  See screenshots below for before save, after one save, and after two saves.  The behavior is inconsistent and doesn't impact every portion of the file.  I am on 1.4.0.

![smarty1](https://user-images.githubusercontent.com/37425083/81843898-4b1c7300-951c-11ea-9a36-1066deda5f8e.PNG)

![smarty2](https://user-images.githubusercontent.com/37425083/81843931-57a0cb80-951c-11ea-9d9a-b0868186908d.PNG)

![smarty3](https://user-images.githubusercontent.com/37425083/81843946-5cfe1600-951c-11ea-88ec-27150952435a.PNG)

**Comment by aswinkumar863** [comment] 2020-05-14 04:55
Duplicate of #3

**Closed by aswinkumar863** 2020-05-14 04:55 UTC
